# Generated by Django 2.0.3 on 2018-05-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0003_use_many_to_many_time_slots"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaignbookingcost",
            name="booking_sheet",
        ),
        migrations.RemoveField(
            model_name="campaignbookingcost",
            name="time_slots",
        ),
        migrations.AddField(
            model_name="bookingsheet",
            name="cost",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookingsheet",
            name="time_slots",
            field=models.ManyToManyField(to="campaigns.TimeSlot"),
        ),
        migrations.DeleteModel(
            name="CampaignBookingCost",
        ),
    ]
