# Generated by Django 2.1.7 on 2019-02-25 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_drop_campaign_booking_cost_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingsheet',
            name='time_slots',
        ),
    ]
