# Generated by Django 3.0.3 on 2020-02-06 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsheet',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_sheets', to='campaigns.Campaign'),
        ),
    ]
