# Generated by Django 3.0.3 on 2020-02-06 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0008_auto_20200206_1204"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material",
                to="campaigns.Campaign",
            ),
        ),
    ]
