# Generated by Django 4.0.5 on 2022-07-24 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0011_alter_bookingsheet_id_alter_campaign_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookedday",
            name="bookingsheet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="campaigns.bookingsheet"
            ),
        ),
    ]
